//
// Created by Yuqiao Miao on 2020/12/6.
//

#ifndef EYERLIB_EVENTSTARTREALTIMEVIDEORESPONSE_HPP
#define EYERLIB_EVENTSTARTREALTIMEVIDEORESPONSE_HPP


class EventStartRealTimeVideoResponse {

};


#endif //EYERLIB_EVENTSTARTREALTIMEVIDEORESPONSE_HPP
